#define NUMBER_OF_SAMPLES 10
#define NUM_VOLTAGES 11
#define VOLTAGE_RES_UNITS
FUNC void memoryvalues(void)
{
	int i;
	
	//formatted decimal display of the array contents
	exec("log > 2DX3_Lab3_Data.txt"); //execute: open up data file
	for(i = 0; i < NUMBER_OF_SAMPLES*NUM_VOLTAGES; i++)  // for loop for 10 samples per 11 voltages
	{
		printf("Sample[%04d] = %04u, Percent of max value: %04u %\n", i, func_m1[i], func_m1[i]/VOLTAGE_RES_UNITS*100); // C format statement
	}
	exec("log off");
	
	//array contents suitable for csv file; csv file is more usable for us
	exec("log > 2DX3_Lab3_Data.csv");
	for(i = 0; i < NUMBER_OF_SAMPLES*NUM_VOLTAGES; i++) // store a total of 110 ADC readings
	{
		printf("%d,%u, Percent of max value: %u %\n", i, func_m1[i], func_m1[i]/VOLTAGE_RES_UNITS); //need to format data output properly. Will indicate index and value
	}
	exec("log off");
}